#include "mainwindow.h"
// imports the neccessarry code for window ddisplay logc

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent) // Parent window is the main window before the invokation of the dialoge boxes and sub menus
    , ui(new Ui::MainWindow) //
{
    ui->setupUi(this);

    // connct menubar actions to their respectve slots
    connect(ui->actionManageFloorsLots, &QAction::triggered, this, &MainWindow::on_actionManageFloorsLots_triggered);
    connect(ui->actionRates, &QAction::triggered, this, &MainWindow::on_actionRates_triggered);
    connect(ui->actionExit, &QAction::triggered, this, &MainWindow::on_actionExit_triggered);

    // initialse the dashboard status banner
    updateDashboardStatus();
}

MainWindow::~MainWindow()
{
    delete ui; // class destructor to destrop the ui memory location upon close
}

// THis function updates the start menu dahsboard so user can see live parkng statistics
void MainWindow::updateDashboardStatus()
{
    unsigned long totalSpots = 0;
    unsigned long occupiedSpots = 0;
    unsigned long floorCount = structures.GetFloorCount();

    for (unsigned long f = 0; f < floorCount; ++f)
    {
        Floor fl = structures.GetFloors(f);
        totalSpots += fl.parkinglots.size();
        for (const auto &lot : fl.parkinglots)
        {
            if (lot.occupied)
            {
                occupiedSpots++;
            }
        }
    }
    unsigned long freeSpots = (totalSpots >= occupiedSpots) ? (totalSpots - occupiedSpots) : 0;
    ui->statusLabel->setText(QString("Floors: %1  |  Total Spots: %2  |  Available: %3  |  Occupied: %4")
        .arg(floorCount)
        .arg(totalSpots)
        .arg(freeSpots)
        .arg(occupiedSpots));
}

bool MainWindow::promptCustomerInfo()
{
    QDialog dialog(this); // THis hs the dialog to reqhest user info
    Ui::CustomerUiDialog customerUi;
    customerUi.setupUi(&dialog);

    if (dialog.exec() == QDialog::Accepted) {
        QString FirstName = customerUi.textEdit->toPlainText().trimmed();
        QString SecondName = customerUi.textEdit_3->toPlainText().trimmed();
        QString VehicleReg = customerUi.textEdit_2->toPlainText().trimmed();
        QString IdNumber = customerUi.textEdit_4->toPlainText().trimmed();
        QString PhoneNumber = customerUi.textEdit_5->toPlainText().trimmed(); // phonenumber field extracted as requested
        // The above few lines gets the customer info frrom the enterd fields and converts tehm to plaintext then cassts to QString variables to be used later
        if (VehicleReg.isEmpty()) {
            QMessageBox::warning(this, "Missing Information", "Please enter at least the Vehicle Registration number.");
            return false; // error  incase data is not entered 
        }

        currentCustomerId = structures.AddCustomer(FirstName.toStdString(), SecondName.toStdString(), IdNumber.toStdString(), PhoneNumber.toStdString());
        currentVehicleReg = VehicleReg;
        currentCustomerName = (FirstName.isEmpty() && SecondName.isEmpty()) ? "Customer" : (FirstName + " " + SecondName);
        currentCustomerPhone = PhoneNumber;
        // THE abobr 3 lines are for casting information to the stdstring and then copying them to the private vars using setters
        qDebug() << "Customer registered:" << currentCustomerName << "Vehicle:" << currentVehicleReg << "Phone:" << currentCustomerPhone; // optional print to console when execution is in place for testing purposes ?? will comment this out later
                                                                                                      // Also becomes unused when compiled with RELEASE Flag on
        return true;
    }
    return false;
}

// Logic to reserve space and add  invoke customer informatn request board 
// Do note that the classes and the skeletopn is generated by qtcreator when designing the UI 
// Do not edit function names laaater oneee
//
void MainWindow::on_reserveButton_clicked()
{
    QDialog dialog(this);
    Ui::ReserveParkingDialog ParkingUi;
    ParkingUi.setupUi(&dialog);

    // Floor combo box selector so user can swithc floors easily
    unsigned long selectedFloor = 0;
    int selectedSpot = -1;
    QPushButton *lastSelectedBtn = nullptr;

    QComboBox *floorCombo = new QComboBox(&dialog);
    floorCombo->setGeometry(60, 15, 120, 28);
    for (unsigned long f = 0; f < structures.GetFloorCount(); ++f)
    {
        floorCombo->addItem(QString("Floor %1").arg(f + 1), static_cast<qulonglong>(f));
    }

    // Helper lambda to refresh the parkign spot grid for any selected floor
    auto populateGrid = [&](unsigned long floorIdx) {
        // clear old widgets from grid
        QLayoutItem *item;
        while ((item = ParkingUi.gridLayout->takeAt(0)) != nullptr) {
            delete item->widget();
            delete item;
        }
        selectedSpot = -1;
        lastSelectedBtn = nullptr;

        Floor currentFloor = structures.GetFloors(floorIdx);
        int totalSpots = static_cast<int>(currentFloor.parkinglots.size());

        for (int i = 0; i < totalSpots; ++i)
        {
            int row = i / 2;
            int col = i % 2;
            int spotId = i;

            QPushButton *spotBtn = new QPushButton(&dialog);
            spotBtn->setMinimumSize(85, 38);

            bool isOccupied = currentFloor.parkinglots[spotId].occupied;
            QString regNumber = QString::fromStdString(currentFloor.parkinglots[spotId].OVehicleReg);

            if (isOccupied)
            {
                spotBtn->setText(QString("Spot %1\n%2").arg(spotId + 1).arg(regNumber));
                spotBtn->setStyleSheet(
                    "background-color: #c62828; color: white; font-weight: bold; "
                    "border-radius: 5px; font-size: 10px;"
                );

                QObject::connect(spotBtn, &QPushButton::clicked, [this, floorIdx, spotId, regNumber]() {
                    this->onOccupiedSpotClicked(floorIdx, spotId, regNumber);
                });
            }
            else
            {
                spotBtn->setText(QString("Spot %1\n[ FREE ]").arg(spotId + 1));
                spotBtn->setStyleSheet(
                    "background-color: #2e7d32; color: white; font-weight: bold; "
                    "border-radius: 5px; font-size: 10px;"
                );

                QObject::connect(spotBtn, &QPushButton::clicked, [this, &selectedSpot, &lastSelectedBtn, spotBtn, spotId, floorIdx]() {
                    if (lastSelectedBtn && lastSelectedBtn != spotBtn) {
                        lastSelectedBtn->setStyleSheet(
                            "background-color: #2e7d32; color: white; font-weight: bold; "
                            "border-radius: 5px; font-size: 10px;"
                        );
                    }

                    selectedSpot = spotId;
                    lastSelectedBtn = spotBtn;
                    spotBtn->setStyleSheet(
                        "background-color: #1565c0; color: white; font-weight: bold; "
                        "border-radius: 5px; font-size: 10px; border: 2px solid yellow;"
                    );

                    this->onSpotSelected(floorIdx, spotId);
                });
            }
            ParkingUi.gridLayout->addWidget(spotBtn, row, col);
        }
    };

    // initialise grid with first floor
    populateGrid(0);

    QObject::connect(floorCombo, QOverload<int>::of(&QComboBox::currentIndexChanged), [&](int index) {
        selectedFloor = static_cast<unsigned long>(index);
        populateGrid(selectedFloor);
    });

    if (dialog.exec() == QDialog::Accepted)
    {
        if (selectedSpot != -1) {
            if (currentVehicleReg.isEmpty()) {
                QMessageBox::information(
                    this,
                    "Customer Details Required",
                    QString("You selected Floor %1, Spot %2.\n\nPlease enter the customer and vehicle registration details to complete this reservation.")
                        .arg(selectedFloor + 1)
                        .arg(selectedSpot + 1)
                );

                if (!promptCustomerInfo()) {
                    qDebug() << "Reservation aborted: User cancelled customer details dialog.";
                    return;
                }
            }

            this->onSpotReservationConfirmed(selectedFloor, selectedSpot, currentVehicleReg);

            currentVehicleReg.clear();
            currentCustomerName.clear();
            currentCustomerPhone.clear();
            updateDashboardStatus();
        } else {
            QMessageBox::warning(this, "No Spot Selected", "Please select an available parking spot before clicking OK.");
        }
    }
    else
    {
        qDebug() << "Reservation Dialog Cancelled";
    }
}

// Also pre generated function skeleton by QT creator
void MainWindow::on_exitButton_clicked()
{
    QStringList occupiedList;
    QList<QPair<unsigned long, int>> spotLocations; // stores floor and spot index

    for (unsigned long f = 0; f < structures.GetFloorCount(); ++f)
    {
        Floor currentFloor = structures.GetFloors(f);
        for (size_t i = 0; i < currentFloor.parkinglots.size(); ++i)
        {
            if (currentFloor.parkinglots[i].occupied)
            {
                QString reg = QString::fromStdString(currentFloor.parkinglots[i].OVehicleReg);
                occupiedList << QString("Floor %1, Spot %2 - %3").arg(f + 1).arg(i + 1).arg(reg);
                spotLocations.append(qMakePair(f, static_cast<int>(i)));
            }
        }
    }

    if (occupiedList.isEmpty())
    {
        QMessageBox::information(this, "Exit & Checkout", "No vehicles are currently parked.");
        return;
    }

    bool ok = false;
    QString selectedItem = QInputDialog::getItem(
        this,
        "Vehicle Checkout",
        "Select occupying vehicle to checkout:",
        occupiedList,
        0,
        false,
        &ok
    );
    // Doalog for exiting vehicles

    if (ok && !selectedItem.isEmpty())
    {
        // Logic for exiting parking lot to calculate charges  duration and also declare the space to be free
        int chosenIndex = occupiedList.indexOf(selectedItem);
        unsigned long floorId = spotLocations[chosenIndex].first;
        int spotId = spotLocations[chosenIndex].second;

        Floor currentFloor = structures.GetFloors(floorId);
        unsigned long checkIn = currentFloor.parkinglots[spotId].CheckInTime;
        unsigned long charges = structures.CalculateCharges(checkIn);
        std::string naturalDuration = structures.GetDurationNatural(checkIn);
        QString reg = QString::fromStdString(currentFloor.parkinglots[spotId].OVehicleReg);

        QMessageBox::information(
            this,
            "Checkout Receipt",
            QString("Checkout Summary:\n\nVehicle: %1\nFloor: %2\nSpot: %3\nDuration: %4\n\nTotal Charges: KES %5\n\nVehicle checked out successfully. Spot is now free.")
                .arg(reg)
                .arg(floorId + 1)
                .arg(spotId + 1)
                .arg(QString::fromStdString(naturalDuration))
                .arg(charges)
        );

        structures.FreeSpace(floorId, spotId);
        qDebug() << "[EXIT] Floor" << (floorId + 1) << "Spot" << (spotId + 1) << "freed for vehicle" << reg << "after" << QString::fromStdString(naturalDuration) << "charges: KES" << charges;
        updateDashboardStatus();
    }
}

// Menu for editing parkng lots to add more and also to add more floors
void MainWindow::on_manageParkingButton_clicked()
{
    QDialog dialog(this);
    dialog.setWindowTitle("Manage Floors & Parking Lots");
    dialog.resize(520, 420);

    QVBoxLayout *mainLayout = new QVBoxLayout(&dialog);

    QLabel *infoLabel = new QLabel("Configure and edit parkng floors and add more parking spaces:", &dialog);
    infoLabel->setStyleSheet("font-weight: bold; font-size: 11pt;");
    mainLayout->addWidget(infoLabel);

    // Floor summary table
    QTableWidget *table = new QTableWidget(&dialog);
    table->setColumnCount(4);
    table->setHorizontalHeaderLabels({"Floor", "Total Spots", "Occupied", "Available"});
    table->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);
    table->setEditTriggers(QAbstractItemView::NoEditTriggers);
    mainLayout->addWidget(table);

    // Lambda to refresh table content
    auto refreshTable = [&]() {
        table->setRowCount(0);
        unsigned long floorCount = structures.GetFloorCount();
        for (unsigned long f = 0; f < floorCount; ++f)
        {
            Floor fl = structures.GetFloors(f);
            unsigned long total = fl.parkinglots.size();
            unsigned long occ = 0;
            for (const auto &lot : fl.parkinglots)
            {
                if (lot.occupied) occ++;
            }
            int row = table->rowCount();
            table->insertRow(row);
            table->setItem(row, 0, new QTableWidgetItem(QString("Floor %1").arg(f + 1)));
            table->setItem(row, 1, new QTableWidgetItem(QString::number(total)));
            table->setItem(row, 2, new QTableWidgetItem(QString::number(occ)));
            table->setItem(row, 3, new QTableWidgetItem(QString::number(total - occ)));
        }
    };
    refreshTable();

    // Controls layout for floor management
    QHBoxLayout *floorBtnLayout = new QHBoxLayout();
    QPushButton *addFloorBtn = new QPushButton("+ Add New Floor", &dialog);
    QPushButton *removeFloorBtn = new QPushButton("- Remove Top Floor", &dialog);
    floorBtnLayout->addWidget(addFloorBtn);
    floorBtnLayout->addWidget(removeFloorBtn);
    mainLayout->addLayout(floorBtnLayout);

    // Controls layout for parkng spot management on selected floor
    QHBoxLayout *spotBtnLayout = new QHBoxLayout();
    QLabel *selectFloorLabel = new QLabel("Select Floor:", &dialog);
    QComboBox *floorSelectCombo = new QComboBox(&dialog);
    auto refreshCombo = [&]() {
        floorSelectCombo->clear();
        for (unsigned long f = 0; f < structures.GetFloorCount(); ++f)
        {
            floorSelectCombo->addItem(QString("Floor %1").arg(f + 1), static_cast<qulonglong>(f));
        }
    };
    refreshCombo();

    QPushButton *addSpotBtn = new QPushButton("+ Add Spot to Floor", &dialog);
    QPushButton *removeSpotBtn = new QPushButton("- Remove Last Spot", &dialog);
    spotBtnLayout->addWidget(selectFloorLabel);
    spotBtnLayout->addWidget(floorSelectCombo);
    spotBtnLayout->addWidget(addSpotBtn);
    spotBtnLayout->addWidget(removeSpotBtn);
    mainLayout->addLayout(spotBtnLayout);

    // Add floor button logic
    QObject::connect(addFloorBtn, &QPushButton::clicked, [&]() {
        bool ok = false;
        int defaultSpots = QInputDialog::getInt(&dialog, "New Floor", "Enter initial number of spots for new floor:", 12, 1, 50, 1, &ok);
        if (ok)
        {
            structures.AddFloor(defaultSpots);
            refreshTable();
            refreshCombo();
            updateDashboardStatus();
            QMessageBox::information(&dialog, "Success", QString("New floor added with %1 spots!").arg(defaultSpots));
        }
    });

    // Remove floor button logic
    QObject::connect(removeFloorBtn, &QPushButton::clicked, [&]() {
        int res = structures.RemoveFloor();
        if (res == -1)
        {
            QMessageBox::warning(&dialog, "Error", "Cannot remove ground floor. Must keep at least one floor!");
        }
        else if (res == -2)
        {
            QMessageBox::warning(&dialog, "Error", "Cannot remove top floor because there are still occupied vehicles parked on it!");
        }
        else
        {
            refreshTable();
            refreshCombo();
            updateDashboardStatus();
            QMessageBox::information(&dialog, "Success", "Top floor removed successfully!");
        }
    });

    // Add spot to selected floor
    QObject::connect(addSpotBtn, &QPushButton::clicked, [&]() {
        int currentIdx = floorSelectCombo->currentIndex();
        if (currentIdx >= 0)
        {
            structures.AddParkingLots(static_cast<unsigned long>(currentIdx), 1);
            refreshTable();
            updateDashboardStatus();
            QMessageBox::information(&dialog, "Success", QString("1 new parking lot added to Floor %1!").arg(currentIdx + 1));
        }
    });

    // Remove spot from selected floor
    QObject::connect(removeSpotBtn, &QPushButton::clicked, [&]() {
        int currentIdx = floorSelectCombo->currentIndex();
        if (currentIdx >= 0)
        {
            int res = structures.RemoveParkingLot(static_cast<unsigned long>(currentIdx));
            if (res == -1)
            {
                QMessageBox::warning(&dialog, "Error", "No spots available to remove on this floor!");
            }
            else if (res == -2)
            {
                QMessageBox::warning(&dialog, "Error", "Cannot remove spot because it is currently occupied!");
            }
            else
            {
                refreshTable();
                updateDashboardStatus();
                QMessageBox::information(&dialog, "Success", QString("Parking lot removed from Floor %1!").arg(currentIdx + 1));
            }
        }
    });

    QPushButton *closeBtn = new QPushButton("Close", &dialog);
    mainLayout->addWidget(closeBtn);
    QObject::connect(closeBtn, &QPushButton::clicked, &dialog, &QDialog::accept);

    dialog.exec();
}

// Section for changign rates and addign new tiers as requested
void MainWindow::on_ratesButton_clicked()
{
    QDialog dialog(this);
    dialog.setWindowTitle("Tariff & Rate Tiers Settings");
    dialog.resize(540, 400);

    QVBoxLayout *mainLayout = new QVBoxLayout(&dialog);

    QLabel *heading = new QLabel("Configured Pricing Tiers and Rates (KES):", &dialog);
    heading->setStyleSheet("font-weight: bold; font-size: 11pt;");
    mainLayout->addWidget(heading);

    QTableWidget *table = new QTableWidget(&dialog);
    table->setColumnCount(4);
    table->setHorizontalHeaderLabels({"Tier", "Description", "Max Duration", "Rate (KES)"});
    table->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);
    table->setSelectionBehavior(QAbstractItemView::SelectRows);
    table->setEditTriggers(QAbstractItemView::NoEditTriggers);
    mainLayout->addWidget(table);

    QLabel *overtimeLabel = new QLabel(&dialog);
    overtimeLabel->setStyleSheet("font-style: italic; color: #555555;");
    mainLayout->addWidget(overtimeLabel);

    // Helper to refresh table with currnt rate tiers
    auto refreshTierTable = [&]() {
        table->setRowCount(0);
        const auto &tiers = structures.GetRateTiers();
        for (size_t i = 0; i < tiers.size(); ++i)
        {
            int row = table->rowCount();
            table->insertRow(row);
            table->setItem(row, 0, new QTableWidgetItem(QString("Tier %1").arg(i + 1)));
            table->setItem(row, 1, new QTableWidgetItem(QString::fromStdString(tiers[i].name)));
            table->setItem(row, 2, new QTableWidgetItem(QString::fromStdString(structures.FormatDuration(tiers[i].maxSeconds))));
            table->setItem(row, 3, new QTableWidgetItem(QString("KES %1").arg(tiers[i].charge)));
        }
        overtimeLabel->setText(QString("Overtime Fee (if duration exceeds all tiers): KES %1").arg(structures.GetMaxOvertimeCharge()));
    };
    refreshTierTable();

    QHBoxLayout *btnLayout = new QHBoxLayout();
    QPushButton *editRateBtn = new QPushButton("Edit Selected Tier Rate", &dialog);
    QPushButton *addTierBtn = new QPushButton("+ Add New Tier", &dialog);
    QPushButton *overtimeBtn = new QPushButton("Set Overtime Fee", &dialog);
    btnLayout->addWidget(editRateBtn);
    btnLayout->addWidget(addTierBtn);
    btnLayout->addWidget(overtimeBtn);
    mainLayout->addLayout(btnLayout);

    // Edit rate logic for selected tier
    QObject::connect(editRateBtn, &QPushButton::clicked, [&]() {
        int selectedRow = table->currentRow();
        if (selectedRow < 0)
        {
            QMessageBox::warning(&dialog, "Selection Required", "Please select a tier row in the table first.");
            return;
        }
        const auto &tiers = structures.GetRateTiers();
        bool ok = false;
        int newRate = QInputDialog::getInt(&dialog, "Edit Rate",
            QString("Enter new rate in KES for %1:").arg(QString::fromStdString(tiers[selectedRow].name)),
            static_cast<int>(tiers[selectedRow].charge), 0, 10000, 10, &ok);
        if (ok)
        {
            structures.UpdateRateTier(static_cast<size_t>(selectedRow), static_cast<unsigned long>(newRate));
            refreshTierTable();
            QMessageBox::information(&dialog, "Success", "Rate updated successfully!");
        }
    });

    // Add new tier logic
    QObject::connect(addTierBtn, &QPushButton::clicked, [&]() {
        bool ok = false;
        QString tierName = QInputDialog::getText(&dialog, "New Tier Name", "Enter name or label for the new tier:", QLineEdit::Normal, "Extended stay", &ok);
        if (!ok || tierName.trimmed().isEmpty()) return;

        int durationHours = QInputDialog::getInt(&dialog, "Duration Limit", "Enter duration upper limit in hours:", 8, 1, 100, 1, &ok);
        if (!ok) return;

        int chargeKes = QInputDialog::getInt(&dialog, "Tier Charge", "Enter fee in KES for this tier:", 500, 0, 20000, 50, &ok);
        if (!ok) return;

        structures.AddRateTier(tierName.toStdString(), static_cast<unsigned long>(durationHours * 3600), static_cast<unsigned long>(chargeKes));
        refreshTierTable();
        QMessageBox::information(&dialog, "Success", QString("New tier '%1' added successfully!").arg(tierName));
    });

    // Overtime fee edit
    QObject::connect(overtimeBtn, &QPushButton::clicked, [&]() {
        bool ok = false;
        int newOvertime = QInputDialog::getInt(&dialog, "Set Overtime Fee",
            "Enter charge in KES for parking duration exceeding all defined tiers:",
            static_cast<int>(structures.GetMaxOvertimeCharge()), 0, 50000, 50, &ok);
        if (ok)
        {
            structures.SetMaxOvertimeCharge(static_cast<unsigned long>(newOvertime));
            refreshTierTable();
            QMessageBox::information(&dialog, "Success", "Overtime fee updated successfully!");
        }
    });

    QPushButton *closeBtn = new QPushButton("Close", &dialog);
    mainLayout->addWidget(closeBtn);
    QObject::connect(closeBtn, &QPushButton::clicked, &dialog, &QDialog::accept);

    dialog.exec();
}

void MainWindow::on_actionManageFloorsLots_triggered()
{
    on_manageParkingButton_clicked();
}

void MainWindow::on_actionRates_triggered()
{
    on_ratesButton_clicked();
}

void MainWindow::on_actionExit_triggered()
{
    QApplication::quit();
}

void MainWindow::onSpotSelected(unsigned long floorId, int spotId)
{
    qDebug() << "User picked Floor:" << (floorId + 1) << "Spot:" << (spotId + 1); // Debug message to console ( plus 1 since the indexes start at 0 )
}

void MainWindow::onOccupiedSpotClicked(unsigned long floorId, int spotId, const QString &vehicleReg)
{
    qDebug() << "Clicked occupied Floor:" << (floorId + 1) << "Spot:" << (spotId + 1) << "Occupant:" << vehicleReg; // Debug message when one selects a parking spot ....
    QMessageBox::information(
        this,
        "Spot Already Occupied",
        QString("Floor %1, Spot %2 is currently occupied.\n\nVehicle Registration: %3")
            .arg(floorId + 1)
            .arg(spotId + 1)
            .arg(vehicleReg)
    ); // Warnign message not to double book a place
}

// Event for reserving spot and declaring checkin time and all
void MainWindow::onSpotReservationConfirmed(unsigned long floorId, int spotId, const QString &vehicleReg)
{
    QString reg = vehicleReg.isEmpty() ? "UNREGISTERED" : vehicleReg;

    int result = structures.SelectSpace(reg.toStdString(), floorId, spotId, currentCustomerId);

    if (result == 0) {
        qDebug() << "[SUCCESS] Floor" << (floorId + 1) << "Spot" << (spotId + 1) << "assigned to vehicle:" << reg;
        QMessageBox::information(
            this,
            "Reservation Confirmed",
            QString("Spot %1 on Floor %2 has been successfully reserved for vehicle:\n%3")
                .arg(spotId + 1)
                .arg(floorId + 1)
                .arg(reg)
        );
    } else {
        qDebug() << "[ERROR] Could not reserve Floor" << (floorId + 1) << "Spot" << (spotId + 1);
        QMessageBox::critical(
            this,
            "Error",
            QString("Could not reserve Floor %1 Spot %2. It may already be occupied.").arg(floorId + 1).arg(spotId + 1)
        ); // INcase the reservation fails (Hoever this part may not be reached since if occupied it would be already flagged earluer on as the spot is not clickable)
    }
}
