#include "mainwindow.h" //Includes the file which has the window UI rendering logic 
                        //THe window rendering header files are generated by qt creator from the .ui file (uses CMakelists.txt from Window folder)

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w; // Delares the Window UI object (the starting point)
    w.show(); // Invokes the method to render the window
    return QApplication::exec(); // return value of success from show exec window inside namespace of QApplication
}
